import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiFillTwitterCircle } from "react-icons/ai";
import { FaBootstrap, FaCss3Alt, FaFigma, FaGithubSquare, FaHtml5, FaLaravel, FaPhp, FaReact } from "react-icons/fa";
import { GrMysql } from "react-icons/gr";
import { SiJavascript, SiTailwindcss } from "react-icons/si";
import { FiChevronDown } from "react-icons/fi";
import Image from "next/image";
import profilePic from "../public/pedrolucas-profile-pic.jpg";
import model3d from "../public/3d.png";
import design from "../public/design-test.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Pedro Lucas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="
      bg-white dark:bg-black 
      px-4 sm:px-4 md:px-8 lg:px-60
      transition-all duration-500
      ">

        <section className="min-h-screen">
          <nav className="py-10 mb-6 flex justify-between items-center">
            <h1 className="text-lg font-worksans dark:text-gray-50">Pedro Lucas</h1>
            <ul className="flex items-center">
              <li>
                <a className=" text-neutral-400 py-2 rounded-full mr-8 transition-all duration-1000 hover:shadow-lg hover:text-neutral-100" href="https://github.com/pedrolucaslcosta" target="_blank" rel="noreferrer">
                  Github
                </a>
              </li>
              <li>

                {darkMode ? (
                  <BsFillSunFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-neutral-700 dark:text-neutral-50 dark:hover:text-neutral-400 hover:text-neutral-500 transition-all duration-500 hover:animate-spin" />
                ) :
                  (
                    <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-neutral-700 dark:text-neutral-50 dark:hover:text-neutral-400 hover:text-neutral-500 transition-all duration-500 hover:animate-pulse" />
                  )}

              </li>

              <li>
                <a className="bg-gradient-to-r from-sky-600 to-sky-700 text-white px-5 py-2 rounded-full ml-8 transition-all duration-1000 hover:shadow-lg">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="grid grid-cols-3 gap-4">

            <div className=" 
            col-span-3 lg:col-span-2 md:col-span-2 sm:col-span-3
            border-neutral-700 border
            rounded-2xl lg:p-10 sm:p-8 p-6
            ">
              <h2 className="text-3xl sm:text-5xl font-semibold text-neutral-900 dark:text-neutral-200">Hello World🖱️</h2>
              {/* <h3 className="text-xl sm:text-2xl py-1 sm:py-2 text-neutral-500 dark:text-gray-400">Developer and designer.</h3> */}
              <p className="text-base sm:text-md pt-5 pb-8 sm:py-5 text-gray-500 dark:text-gray-400">
                {"I'm a Junior Frontend Developer and UI/UX Designer. Technician in Internet Computing at the Federal Institute of Rio Grande do Norte (IFRN) and studying Graphic Design at the Potiguar University (UnP). Currently working with Laravel and studying React.js."}
              </p>
              <div className="text-base sm:text-xl flex justify-center sm:justify-start gap-3 sm:gap-4 text-black">
                <a href="mailto:pedrolucaslcosta@gmail.com" target="_blank" rel="noreferrer" className="text-sm font-semibold rounded-full bg-sky-800 text-sky-100 flex items-center px-5">
                  Contact me
                </a>
                <a href="https://www.instagram.com/pedrolucaslco" target="_blank" rel="noreferrer" className="bg-sky-800 p-3 rounded-full dark:bg-sky-800 dark:text-sky-100">
                  <AiFillInstagram />
                </a>
                <a href="https://www.linkedin.com/in/pedrolucaslcosta" target="_blank" rel="noreferrer" className="bg-sky-800 p-3 rounded-full dark:bg-sky-800 dark:text-sky-100">
                  <AiFillLinkedin />
                </a>
                <a href="https://www.twitter.com/pedrolucaslco" target="_blank" rel="noreferrer" className="bg-sky-800 p-3  rounded-full dark:bg-sky-800 dark:text-sky-100">
                  <AiFillTwitterCircle />
                </a>
              </div>
            </div>

            <div className="
            col-span-3 lg:col-span-1 md:col-span-1 order-first sm:order-first md:order-2 h-64 sm:h-96
            rounded-3xl">
              <Image className="rounded-2xl h-full w-full object-scale-down sm:object-scale-down md:object-cover border-neutral-700 border" src={model3d} />
            </div>

            
          </div>

          <div className="p-5 mt-4 rounded-2xl border-neutral-700 border flex flex-col items-center">
            <div className="text-base sm:text-xl flex justify-center sm:justify-start gap-3 sm:gap-4 text-black flex-wrap">
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaLaravel /><span>Laravel</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaGithubSquare /><span>Git</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaPhp /><span>PhP</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaHtml5 /><span>HTML</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaCss3Alt /><span>CSS</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaFigma /><span>Figma</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><GrMysql /><span>MySql</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaReact /><span>React.js</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><FaBootstrap /><span>Bootstrap</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><SiJavascript /><span>Javascript</span></a>
              <a title="test" id="tools" className="p-3 rounded-2xl border-neutral-700 border text-sky-100"><SiTailwindcss /><span>TailwindCSS</span></a>
            </div>  
          </div>

          {/* <div className="p-10 pb-5 mt-4 rounded-2xl
          border-neutral-700 border flex flex-col items-center
          ">
              <h3 className="text-3xl font-bold dark:text-neutral-300 text-center">Projects</h3>
              <p className="text-md text-neutral-400 text-center">
                Check it out
              </p>
              <a href="#projetos" className="text-black bg-white flex items-center px-3 py-2 rounded-full font-semibold text-sm">
                Quero conferir
                <FiChevronDown />
              </a>
              
            
          </div> */}

          {/* <div id="projetos" className="grid grid-cols-3 gap-4 my-4">

            <div className="bg-neutral-700 rounded-2xl col-span-1 flex flex-col justify-end
            hover:bg-neutral-400 hover:transition-all hover:duration-700 hover:opacity-30
            ">
              
                <Image src={design} className="rounded-t-2xl grow"/>
                <div className="px-4 py-2 flex flex-col overflow-hidden">
                  <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                  <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
                </div>
              

              
                 
            </div>

            <div className="bg-neutral-700 rounded-2xl col-span-2">
              <div className="">
                <Image src={design} className="rounded-t-2xl"/>
              </div>
              <div className="px-4 py-2 flex flex-col">
                <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
              </div>   
            </div>

            <div className="bg-neutral-700 rounded-2xl col-span-1">
              <div>
                <Image src={design} className="rounded-t-2xl bg-cover"/>
              </div>
              <div className="px-4 py-2 flex flex-col">
                <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
              </div>   
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 my-4">
            <div className="bg-neutral-700 rounded-2xl col-span-1">
              <div>
                <Image src={design} className="rounded-t-2xl bg-cover"/>
              </div>
              <div className="px-4 py-2 flex flex-col">
                <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
              </div>   
            </div>

            <div className="bg-neutral-700 rounded-2xl col-span-1">
              <div>
                <Image src={design} className="rounded-t-2xl bg-cover"/>
              </div>
              <div className="px-4 py-2 flex flex-col">
                <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
              </div>   
            </div>

            <div className="bg-neutral-700 rounded-2xl col-span-1">
              <div>
                <Image src={design} className="rounded-t-2xl bg-cover"/>
              </div>
              <div className="px-4 py-2 flex flex-col">
                <a href="" className="text-neutral-100 text-base">Studio Seven</a>
                <a href="" className="text-neutral-400 text-sm font-semibold uppercase">Branding</a>
              </div>   
            </div>
          </div>
           */}
        
        </section>

      </main>
    </div>
  )
}
